---
shared:
- bedelias_name: "INGENIERÍA EN COMPUTACIÓN"
  id: "computacion"
  current_plan: "1997"
- bedelias_name: "INGENIERÍA ELÉCTRICA"
  id: "electrica"
  current_plan: "2023"
  include_inco_subjects: false
