---
shared:
- bedelias_name: "INGENIERÍA EN COMPUTACIÓN"
  id: "computacion"
  name: "Ingeniería en Computación"
  current_plan: "1997"
- bedelias_name: "INGENIERÍA ELÉCTRICA"
  id: "electrica"
  name: "Ingeniería Eléctrica"
  current_plan: "2023"
